# Generated by Django 5.0.1 on 2024-02-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_contenu_contenttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenu',
            name='citation_auteur',
            field=models.CharField(default='Test Test', max_length=200),
            preserve_default=False,
        ),
    ]
