# Generated by Django 5.0.1 on 2024-02-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_alter_article_content_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blogsite.contenu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blogsite.contenu'),
        ),
    ]
