# Generated by Django 5.0.1 on 2024-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0007_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
