# Generated by Django 5.0.1 on 2024-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0008_alter_test_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='upload',
            field=models.FileField(upload_to='blogsite/static/blog'),
        ),
    ]
