# Generated by Django 5.0.1 on 2024-02-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0011_alter_article_image_alter_article_image_illus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
