# Generated by Django 5.0.1 on 2024-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0012_article_slug_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.CharField(max_length=100)),
                ('date_fin', models.CharField(max_length=100)),
            ],
        ),
    ]
