# Generated by Django 5.0.1 on 2024-02-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0013_statuser_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuser',
            name='token',
            field=models.CharField(default='aeetze', max_length=500),
            preserve_default=False,
        ),
    ]
