# Generated by Django 5.0.1 on 2024-02-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0014_article_views_statuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuser',
            name='token',
        ),
    ]
