# Generated by Django 5.0.1 on 2024-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0015_remove_statuser_token_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuser',
            name='int_debut',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statuser',
            name='int_fin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
